export MCDIR=/eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/07Jun2016_spring16_mAODv2_12pXfbm1_repro/MCl2loose__hadd__bSFL2pTEff__l2tight__vh3lSel/

gardener.py l3kinfiller $MCDIR/latino_HZJ_HToWW_M125.root latino_HZJ_HToWW_M125.root
gardener.py l3kinfiller $MCDIR/latino_ggZH_HToWW_M125.root latino_ggZH_HToWW_M125.root

gardener.py l3kinfiller $MCDIR/latino_TTZToLLNuNu_M-10.root latino_TTZToLLNuNu_M-10.root 
gardener.py l3kinfiller $MCDIR/latino_WWZ.root latino_WWZ.root
gardener.py l3kinfiller $MCDIR/latino_WWW.root latino_WWW.root
gardener.py l3kinfiller $MCDIR/latino_WZZ.root latino_WZZ.root
gardener.py l3kinfiller $MCDIR/latino_WZTo3LNu.root latino_WZTo3LNu.root
gardener.py l3kinfiller $MCDIR/latino_ZZTo4L.root latino_ZZTo4L.root

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_DoubleEG.root latino_Run2016B_PromptReco_DoubleEG_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_DoubleMuon.root latino_Run2016B_PromptReco_DoubleMuon_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_SingleMuon.root latino_Run2016B_PromptReco_SingleMuon_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_SingleElectron.root latino_Run2016B_PromptReco_SingleElectron_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_MuonEG.root latino_Run2016B_PromptReco_MuonEG_1.root 

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_DoubleEG.root latino_Run2016B_PromptReco_DoubleEG_2.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_DoubleMuon.root latino_Run2016B_PromptReco_DoubleMuon_2.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_SingleMuon.root latino_Run2016B_PromptReco_SingleMuon_2.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_SingleElectron.root latino_Run2016B_PromptReco_SingleElectron_2.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_MuonEG.root latino_Run2016B_PromptReco_MuonEG_2.root 

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_DoubleEG.root latino_Run2016B_PromptReco_DoubleEG_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_DoubleMuon.root latino_Run2016B_PromptReco_DoubleMuon_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_SingleMuon.root latino_Run2016B_PromptReco_SingleMuon_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_SingleElectron.root latino_Run2016B_PromptReco_SingleElectron_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016B_PromptReco_MuonEG.root latino_Run2016B_PromptReco_MuonEG_3.root 

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_MuonEG.root latino_Run2016C_PromptReco_MuonEG_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_DoubleMuon.root latino_Run2016C_PromptReco_DoubleMuon_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_SingleMuon.root latino_Run2016C_PromptReco_SingleMuon_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_DoubleEG.root latino_Run2016C_PromptReco_DoubleEG_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_SingleElectron.root latino_Run2016C_PromptReco_SingleElectron_1.root 

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_MuonEG.root latino_Run2016C_PromptReco_MuonEG_2.root  
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_DoubleMuon.root latino_Run2016C_PromptReco_DoubleMuon_2.root  
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_SingleMuon.root latino_Run2016C_PromptReco_SingleMuon_2.root  
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_DoubleEG.root latino_Run2016C_PromptReco_DoubleEG_2.root  
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_SingleElectron.root latino_Run2016C_PromptReco_SingleElectron_2.root  

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_MuonEG.root latino_Run2016C_PromptReco_MuonEG_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_DoubleMuon.root latino_Run2016C_PromptReco_DoubleMuon_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_SingleMuon.root latino_Run2016C_PromptReco_SingleMuon_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_DoubleEG.root latino_Run2016C_PromptReco_DoubleEG_3.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016C_PromptReco_SingleElectron.root latino_Run2016C_PromptReco_SingleElectron_3.root 

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_MuonEG.root latino_Run2016D_PromptReco_MuonEG_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_DoubleMuon.root latino_Run2016D_PromptReco_DoubleMuon_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_SingleMuon.root latino_Run2016D_PromptReco_SingleMuon_1.root      
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_DoubleEG.root latino_Run2016D_PromptReco_DoubleEG_1.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_SingleElectron.root latino_Run2016D_PromptReco_SingleElectron_1.root 

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_MuonEG.root latino_Run2016D_PromptReco_MuonEG_2.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_DoubleMuon.root latino_Run2016D_PromptReco_DoubleMuon_2.root 
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_SingleMuon.root latino_Run2016D_PromptReco_SingleMuon_2.root    
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_DoubleEG.root latino_Run2016D_PromptReco_DoubleEG_2.root     
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__l2tight__vh3lSel/latino_Run2016D_PromptReco_SingleElectron.root latino_Run2016D_PromptReco_SingleElectron_2.root 


gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_DoubleEG.root latino_Run2016B_PromptReco_DoubleEG_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_DoubleMuon.root latino_Run2016B_PromptReco_DoubleMuon_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_SingleMuon.root latino_Run2016B_PromptReco_SingleMuon_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_SingleElectron.root latino_Run2016B_PromptReco_SingleElectron_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/21Jun2016_v2_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_MuonEG.root latino_Run2016B_PromptReco_MuonEG_fake1.root

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_DoubleEG.root latino_Run2016B_PromptReco_DoubleEG_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_DoubleMuon.root latino_Run2016B_PromptReco_DoubleMuon_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_SingleMuon.root latino_Run2016B_PromptReco_SingleMuon_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_SingleElectron.root latino_Run2016B_PromptReco_SingleElectron_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/05Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_MuonEG.root latino_Run2016B_PromptReco_MuonEG_fake2.root

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_DoubleEG.root latino_Run2016B_PromptReco_DoubleEG_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_DoubleMuon.root latino_Run2016B_PromptReco_DoubleMuon_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_SingleMuon.root latino_Run2016B_PromptReco_SingleMuon_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_SingleElectron.root latino_Run2016B_PromptReco_SingleElectron_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016B_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016B_PromptReco_MuonEG.root latino_Run2016B_PromptReco_MuonEG_fake3.root

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_MuonEG.root latino_Run2016C_PromptReco_MuonEG_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_DoubleMuon.root latino_Run2016C_PromptReco_DoubleMuon_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_SingleMuon.root latino_Run2016C_PromptReco_SingleMuon_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_DoubleEG.root latino_Run2016C_PromptReco_DoubleEG_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/08Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_SingleElectron.root latino_Run2016C_PromptReco_SingleElectron_fake1.root  

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_DoubleEG.root latino_Run2016C_PromptReco_DoubleEG_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_DoubleMuon.root latino_Run2016C_PromptReco_DoubleMuon_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_SingleMuon.root latino_Run2016C_PromptReco_SingleMuon_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_SingleElectron.root latino_Run2016C_PromptReco_SingleElectron_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/11Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_MuonEG.root latino_Run2016C_PromptReco_MuonEG_fake2.root

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_DoubleEG.root latino_Run2016C_PromptReco_DoubleEG_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_DoubleMuon.root latino_Run2016C_PromptReco_DoubleMuon_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_SingleMuon.root latino_Run2016C_PromptReco_SingleMuon_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_SingleElectron.root latino_Run2016C_PromptReco_SingleElectron_fake3.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016C_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016C_PromptReco_MuonEG.root latino_Run2016C_PromptReco_MuonEG_fake3.root

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_DoubleEG.root latino_Run2016D_PromptReco_DoubleEG_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_DoubleMuon.root latino_Run2016D_PromptReco_DoubleMuon_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_SingleMuon.root latino_Run2016D_PromptReco_SingleMuon_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_SingleElectron.root latino_Run2016D_PromptReco_SingleElectron_fake1.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/15Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_MuonEG.root latino_Run2016D_PromptReco_MuonEG_fake1.root

gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_DoubleEG.root latino_Run2016D_PromptReco_DoubleEG_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_DoubleMuon.root latino_Run2016D_PromptReco_DoubleMuon_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_SingleMuon.root latino_Run2016D_PromptReco_SingleMuon_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_SingleElectron.root latino_Run2016D_PromptReco_SingleElectron_fake2.root
gardener.py l3kinfiller /eos/cms/store/group/phys_higgs/cmshww/amassiro/HWW12fb_repro/26Jul2016_Run2016D_PromptReco_repro/l2loose__hadd__ICHEPjson__EpTCorr__fakeW12fb__vh3lFakeSel/latino_Run2016D_PromptReco_MuonEG.root latino_Run2016D_PromptReco_MuonEG_fake2.root
# 
